[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "srutils"
version = "0.1"
dependencies = []
description = "A collection of utilities for system research."
